CaixaEmp.WebUI/Models/ErrorViewModel.cs
namespace CaixaEmp.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CaixaEmp.WebUI/Controllers/ExpenseController.cs
using AutoMapper;
using CaixaEmp.Application.DTOs;
using CaixaEmp.Application.Interfaces;
using CaixaEmp.Domain.Interfaces;
using CaixaEmp.Infra.Data.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace CaixaEmp.WebUI.Controllers
{
    public class ExpenseController : Controller
    {
       
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IExpenseService _expenseService;
        public ExpenseController(IExpenseService expenseService, ApplicationDbContext applicationDbContext)
        {            
            _applicationDbContext = applicationDbContext;
            _expenseService = expenseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var expense = await _expenseService.GetAllExpenseAsync();
            return View(expense);
        }

        //Filtra a busca por nome das despesas "Expense"
        [HttpPost]
        public async Task<IActionResult> Index(string txtProcurar)
        {            
            if (!string.IsNullOrEmpty(txtProcurar))
                return View(await _applicationDbContext.Expenses.Where(e => e.Name.ToUpper().Contains(txtProcurar.ToUpper()))
                    .Select(dto => new ExpenseDTO
                {
                    Name = dto.Name,    
                    Description = dto.Description
                }).ToListAsync());                
            return View(await _expenseService.GetAllExpenseAsync());
            

        }

        [HttpGet]
        public IActionResult Create() 
        {
            ViewData["Id"] = new SelectList(_applicationDbContext.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExpenseDTO expense)
        {
            if(ModelState.IsValid)
            {
                TempData["Confirmacao"] = expense.Name + " foi cadastrada com sucesso.";
                await _expenseService.Create(expense);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_applicationDbContext.Categories, "CategoryId", "Name");
            return View(expense);
        }
    }
}

CaixaEmp.WebUI/Views/Expense/Create.cshtml
@model CaixaEmp.Application.DTOs.ExpenseDTO


@{
    ViewData["Title"] = "Registrar nova despesa";
}

<h2>@ViewData["Title"]</h2>
<form asp-action="Create" method="post">
    <div class="form-horizontal">
        <hr/>
        <div asp-validation-summary="All" class="text-dark"></div>

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label">Nome</label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-group"/>
                <span asp-validation-for="Name" class="text-black"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label">Descrição</label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-group" />
                <span asp-validation-for="Description" class="text-black"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ExpenseCategoryId" class="col-md-2 control-label">Categoria</label>
            <div class="col-md-10">
                <select asp-for="ExpenseCategoryId" class="form-control" asp-items="ViewBag.Id"></select>
                <span asp-validation-for="ExpenseCategoryId" class="text-danger"></span>
            </div>
        </div>
        <br/>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-outline-success" />
                <a asp-action="Index" class="btn btn-outline-dark">Voltar a lista</a>
            </div>
        </div>
    </div>
</form>

CaixaEmp.WebUI/Views/Expense/Index.cshtml
@model IEnumerable<CaixaEmp.Application.DTOs.ExpenseDTO>

@{
    ViewData["Title"] = "Index";
}

<p class="btnNovo">
    
</p>

@if(TempData["Confirmacao"] != null)
{
    <h6 class="alert alert-success">@TempData["Confirmacao"]</h6>
}
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" type="button" class="btn btn-outline-dark">
                    Criar nova despesa
                </a>
                
            </div>
        </div>
    </div>
</div>
<br/>
<form asp-action="Index" asp-controller="Expense" method="post">
    <div class="form-group">
        <div class="input-group col-md-6">
            <input class="form-group" name="txtProcurar"/>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-dark"><i class="fas fa-search-plus"></i></button>
            </div>
        </div>
    </div>
</form>
<br/>
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-dark">Editar</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-dark">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CaixaEmp.WebUI/Views/Home/Index.cshtml
@model IEnumerable<CaixaEmp.Domain.Entities.Expense>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Criar nova Despesa</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayNameFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayNameFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayNameFor(modelItem => item.Value)
                </td>
                <td>
                    @Html.DisplayNameFor(modelItem => item.Priority)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Deleção</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CaixaEmp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CaixaEmp.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"/>
    <link rel="stylesheet" href="~/CaixaEmp.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Expense" asp-action="Index">Controle de Caixa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emplooyer" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Expense" asp-action="Index">Despesas</a>
                        </li>
                    </ul>
                    @*<form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">Buscar</button>
                    </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CaixaEmp.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>     
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>